services:
  database:
    networks:
      - identity
    container_name: identity-mongodb
    image: mongo:latest
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./.mongodb-identity:/data/db
    ports:
      - ${DATABASE_BIND_PORT}:27017
    command: ["mongod", "--port", "27017"]

  api:
    depends_on:
      - database
    networks:
      - identity
    container_name: identity-api
    build:
      context: .
    image: api
    env_file:
      - .env
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - ${APPLICATION_BIND_PORT}:3000

networks:
  identity:
    driver: bridge
